### ISSUE TITLE
Move to TypeScript?

### ISSUE THREAD

**Issue by gil0mendes** [StellarFw/stellar#122]
Ok, I understand that is a hard step, but this may give a solid work base for features and make the maintenance easier. The code will look cleaner because it can be easily traversed and we can understand relationships much better. And there are several common mistakes (that can lead to bugs) that TypeScript checks for us.

More than that, with a language with static types we can better integrate with tools and IDEs to make our development experience better.

What is your opinion on this matters?!

**Comment by rafaelramalho19** [comment]
I approve this suggestion 👍

**Comment by gil0mendes** [comment]
All features, except the chat rooms, were been ported to TS.

The chat room features will need to be rethought to address some current problem that doesn't provide good mechanisms for data protection, like authentication.
