### ISSUE TITLE
stellar does not restore terminal's default color

### ISSUE THREAD

**Issue by siliconforks** [StellarFw/stellar#24]
The `stellar` command colorizes terminal output but it does not restore the terminal's default color.  This means the color may persist even after the `stellar` command terminates.  Depending on your terminal and settings, this may not be noticeable - for example, if you have your shell prompt configured to output colors, it will immediately overwrite whatever color `stellar` set the terminal to.  But if your shell prompt does not output colors, the result will look like this:

![terminal](https://cloud.githubusercontent.com/assets/1156399/18482113/3d1a5be0-79b5-11e6-9840-ad550f89eb5f.png)

**Comment by gil0mendes** [comment]
Yap... I don't notice that, one time I use ZSH with a fancy theme... kkk

Thanks for the report 😉
