### ISSUE TITLE
Add a way to manipulate the action metadata

### ISSUE THREAD

**Issue by gil0mendes** [StellarFw/stellar#26]
The ideia is create a mechanism who allows developers manipulate meta data from the other modules. For example, if I enable the `Identify` module on my application the `auth.register` action is public by default, but I need that action be only called by admins. And there is no way to manipulate that without rewrite the action or patch the action manually.

This need more discussion and usage examples.

**Comment by ivoribeiro** [comment]
Add a method on action that can gange the private property and re-run the engine ?

**Comment by ivoribeiro** [comment]
Is better to reload only the action file

**Comment by gil0mendes** [comment]
@ivoribeiro you don't need reload the file, if you do that your changes will be lost. The ideia is create a mechanism to edit all the metadata and not only the visibility of the action.

Why? Because, on the example I give on the issue description, in that casa, I want apply a middleware on the `auth.register`.
