### ISSUE TITLE
Add support to unit testing

### ISSUE THREAD

**Issue by gil0mendes** [StellarFw/stellar#4]
The Stellar should provide a series of methods and mechanisms to improve and accelerate the writing and execution of unit tests.

**This need some planning and discussion!**

**Comment by jaimetotal** [comment]
What do you mean by this issue?

**Comment by gil0mendes** [comment]
@jaimetotal I need to describe the Api and all the mechanic behind it, but I don't think well on this.

The ideia is create an easy way to write unit testing for the modules. Test the behaviour of the actions simulating calls and that king of stuff.

**Comment by gil0mendes** [comment]
This is already implemented. Now we can use the `stellar test` command on an application root folder and the tests of active modules will be executed.

Now we need add some documentation for the next release.
