### ISSUE TITLE
A Better Talk

### ISSUE THREAD

**Issue by gil0mendes** [StellarFw/stellar#75]
The idea is creating a new event system to allow easily bidirectional communications between the server and the client. This will imply modifications on the chat room system (on the server side), and on the client library, in order to allow send and receive when an event happens.

## Data Structure

An event is just a message with a specific format. The standard format for that is the following:
 
```json
{
  "event": "event_name",
  "data": { "some": "data sent by the server" }
}
```

## Client Side Usage

On the client side, the idea is to be able to send and receive events in a specific chat room. This doesn't invalidate the current implementation, this only extends and adds a more simple way to react when something happens in a chat room.

```js
// receive an event (all rooms)
stellar.on('event_name', (arguments, rawDetails) => { console.log(`> ${arguments}, - ${rawDetails}`) })

// receive an event filtered by room
stellar.on('room_name', 'event_name', arguments => { console.log(`Hello :D (${arguments})`)  })
```

### New Option to Set the Default Room

Now there is a way to set a default room, where all the events are sent, except when the `.emit()` method is used with the room name. This allows the developer omit the room name when calling the `.emit()` method.

You can define the default room name using a parameter, when constructing the StellarClient instance, using the `defaultRoom` options (you can also define it on the server side, as a default preference for clients).

```js
stellar.setDefaultRoom('new_default_room')
```

### Send an Event

In replace of the `.say()` method, the `.emit()` can send an event to the server using just two arguments. This sends the event to the default room when there is no room specified (you can see more about this on above).

```js
// send an event to the default room
stellar.emit('event_name', arguments)

// send an event to a specific room
stellar.emit('room_name', 'event_name', arguments)
````

### Send a `message` Event

The method `.say()` must be modified in order to allow an ease way to send a generic event. This event is from type `message`.

```js
// send a message to the default room
stellar.say([ 'can', 'be', 'any', 'type' ])

// send a message to a specific room
stellar.say('room_name', [ 'can', 'be', 'any', 'type' ])
```

### Join a Chat Room

The method `.roomAdd()` must be renamed to `.join()`. This method allows the client join a chat room by their name.

```js
stellar.join('room_name')
```

### Leave a Chat Room

The `.roomLeave()` method must be renamed to `.leave()`. This method allows client leave a chat room.

```js
stellar.leave('room_name')
```

## Server Implementation

On the current implementation, it's hard to get all the sockets in a chat room, as well perform other simple and complex operation, the general API must be rewritten in order to meet the changes in this document.

### List of Rooms

The `.list()` must be changed in order to return a promise, instead of receiving a callback. This method allows us to get a list of all existing rooms on the system.

```js
const rooms = await api.chatRoom.list()
```

### Broadcast

The `.broadcast` method must be modified in order to simplify the way that we send a message to all clients in a room. This throws an exception if an error occurs.
 
```js
await api.chatRoom.broadcast('room_name', 'some message, can be an object')
```

### Create a Room

The `.add` method must be renamed to `. create()` and changed in order to return a promise. When an error occurs during the room creation, an exception is thrown.

```js
await api.chatRoom.create('room_name')
```

### Remove a Room

The `.destroy()` method must be changed in order to return a promise. When an error occurs during the room removal, an exception is thrown.

```js
await api.chatRoom.destroy('room_name')
```

### Check if the Room Exists

The `.exists()` method must be changed in order to return a promise. When the room exists a `true`  is returned, otherwise `false`.

```js
const found = await api.chatRoom.exists('room_name')
```

### Gets the Room State

The `.roomStatus()` method must be renamed to `.status()` and changed in order to return a promise.

```js
const status = await api.chatRoom.status('room_name')
```

### Add a Member

The `.addMember()` method must be renamed to `join` and must start using promises. The returned value must be a boolean.

```js
const wasAdded = await api.chatRoom.join(clientConnection, 'room_name')
```

### Remove a Member

The `.removeMember()` method must be renamed to `.leave()` and must start using promise. The returned value must be a boolean.

```js
const wasRemoved = await api.chatRoom.leave(connection, 'room_name')
```

### Send a Message to a Specific Client

Each connection has a `.sendMessage()` method to allow you send a message to a specific client. This method must be renamed to `.send()`. This will send a event of the message type, to the client.

```js
connectionObj.send('Welcome to Stellar :)')
```

A new method called `.emit()` must be created in order to send a specific event to a client.

```js
connectionObj.emit('event_name', { some: 'data' })
```

____

This still a working in progress and all contributions are welcome.

**Comment by ivoribeiro** [comment]
Can client-side event listening be used with Promises ?

**Comment by gil0mendes** [comment]
@ivoribeiro We need to have a way to handle all events of one type, and for that, we need a callback pattern. Using a Promise in this scenario only will make able to handle the first event, since that the returned Promise from the `.on()` method would be resolved (you can only use a Promise once).

The other scenario is using the `.on()` method to pause a function execution until receiving a certain event type, and in that case, that would be viable to use a Promise.

Is that second scenario, that are you talking about?

**Comment by jaimetotal** [comment]
To create a room, it should be '.create()' instead of '.add()'. The '.destroy()' is correct.

**Comment by gil0mendes** [comment]
Hey @jaimetotal, first of all, thanks for the message ;)

- Yes, you are right, the right name for the method to create a new room must be `.create()` instead of `.add()`.
- I think that must be a good idea, no? Btw, are you seeing a good way to do that? Maybe add a second parameter to the handler (`.on('event_name', (data, { room }) => {})`)?
- Are you talking about the `.list()` method? If yes, the idea is to get the list of all registered room (this is server side).
- At the start, I thought in to keep the old way (no events) and apply this new system above that, but using just event can be just fine.
- Are you referring from the client?

**Comment by gil0mendes** [comment]
I add some new methods and changes, mainly on the client side.

**Comment by jaimetotal** [comment]
> I think that must be a good idea, no? Btw, are you seeing a good way to do that? Maybe add a second parameter to the handler (.on('event_name', (data, { room }) => {}))?
I agree with that.

>Are you talking about the .list() method? If yes, the idea is to get the list of all registered room (this is server side).
How can a member get a list of available rooms?

>Are you referring from the client?
Yup.

**Comment by gil0mendes** [comment]
I think that this is finally implemented.
