### ISSUE TITLE
Create wrappers on the models system

### ISSUE THREAD

**Issue by gil0mendes** [StellarFw/stellar#8]
The models system make use of the Mongoose, this makes my life easier 😉 
But we need to implement some wrappers to improve the developer experience and reduce the number of code how is necessary to perform basic operations like: create, retrieve, update or delete. 

``` js
// create
api.models.create('modelName', data, (err, model) => {
  next()
})

// get all 
api.models.findAll('modelName', (err, models) => {
  next()
})

// find
api.models.find('modelName', query, (err, models) => {
  next()
})

// find by ID
api.models.findById('modelName', id, (err, model) => {
  next()
})

// update
api.models.updateById('modelName', id, data, (err, model) => {
  next()
})

// delete
api.models.deleteById('modelName', id, err => {
  next()
})

```

**Comment by gil0mendes** [comment]
@jaimetotal you can give your opinion here, pls 😉

**Comment by jaimetotal** [comment]
Besides the simplicity, it's for the best to be not dependent of mongoose. If per example, if you change the technology tomorrow, all the arguments you provide are still legit?

Also, define your own error code convention which you will translate from mongoose error code.

If tomorrow you use something like Redis, your users won't be affected by it. Or even they can switch to it.

**Comment by gil0mendes** [comment]
For now I will keep the Mongoose, but yes in the future we should create an abstraction and not give the direct access to the Mongoose object.

I also make an update on the Issue texto to include the `findAll('modelName')` to get all the entries, is basically a syntax sugar for `find('modelName', {})`

**Comment by jaimetotal** [comment]
I don't mean to not keep the Mongoose. However, if the users get used to the "err" possible values from Mongoose, when you change the underlayer tecnology, it will break existing code as the errors won't be the same.

**Comment by gil0mendes** [comment]
If the we use the `modelObj.method()` approach, we need to take another step before to use the model. We can't make the models global, so it's necessary to get them from the models repository.

```js
// get model class
let carsModel = api.models.get('car')

// update by id
carsModel.updateById()
```

**Comment by ivoribeiro** [comment]
https://github.com/balderdashy/waterline , what do you think about this .

**Comment by gil0mendes** [comment]
That's could be a good start, but for now we have other priorities. I need start work in fixing some issues on the task system and a way to change action's metadata from other modules.

**Comment by gil0mendes** [comment]
The Waterline solution has some problems, as you can see in this [article](https://kev.inburke.com/kevin/dont-use-sails-or-waterline/). 
But I thinks that is a good start, and in the future we can replace the Waterline with our own solution that uses the same methods as the Waterline. So that doesn't will break existing code.

**Comment by gil0mendes** [comment]
Ok, I merged the new model system on the `dev` branch, now we need update the docs and add some use cases using the new features.
