### ISSUE TITLE
Add support to Promises on tasks

### ISSUE THREAD

**Issue by gil0mendes** [StellarFw/stellar#91]
We must add support to Promises on the tasks system. This will extend the framework support for this amazing syntax.

**Atenttion**: We must keep backwards compatibility for `next()`, this still to be usefull in some cases.

Down bellow there is a example of how that should looks like.
```js
'use strict'

exports.afterCancelRepair = {
  name: 'afterCancelRepair',
  description: 'This returns all the material to the stock and remove all material requests',

  queue: 'default',
  frequency: 0,

  async run (api, param) {
    // do stuff...
  }
}
```

**Comment by ivoribeiro** [comment]
😍
